### ISSUE TITLE
Can we add the entry/ exit functions

### ISSUE THREAD

**Issue by tkhuran** [IBM-Swift/LoggerAPI#6]
``` swift
 func entry(functionName:  String = #function, className: String = #file,lineNumber: Int = #line) {
    verbose("ENTRY ->  " + " \(lineNumber) " + functionName + " in " + ((className as NSString).lastPathComponent as NSString).stringByDeletingPathExtension)
}
 func exit(functionName:  String = #function, className: String = #file,lineNumber: Int = #line) {
    verbose("<- EXIT " + " \(lineNumber) " + functionName + " in " + ((className as NSString).lastPathComponent as NSString).stringByDeletingPathExtension)
}
```

**Comment by rfdickerson** [comment]
Good idea, I think I understand. So just to clarify, should the user explicitly call these entry or exit APIs? Or will they be called automatically by some helper API that allows one to automatically wrap (decorate) a function with the entry and exit functions?

**Comment by tkhuran** [comment]
Yeah, it works very handy in a large app debugging to identify the app flow moving from method to method.

func processData() {
entry()
// do you stuff here
exit()
}

**Comment by ianpartridge** [comment]
Good idea.  I think your `#function`, `#file` and `#line` default parameters will be the location of the `entry()` and `exit()` functions themselves, though - not the callsite.  In other words, the parameters must be passed through, and can't be set via defaults.  I haven't tried it though.

**Comment by ianpartridge** [comment]
@rob-deans has completed this work.
