### ISSUE TITLE
Could not find module 'LoggerAPI' for target 'x86_64-apple-ios-simulator

### ISSUE THREAD

**Issue by WeiLiangTan** [IBM-Swift/LoggerAPI#60]
I have added Swift-JWT through SPM. And LoggerAPI was also added as an dependencies.

Getting this error while try to run on simulator, which is preventing to run the app.

<img width="541" alt="Screenshot 2022-11-17 at 10 53 28 AM" src="https://user-images.githubusercontent.com/8586548/202343498-83a69705-581e-4a36-bf8f-9b4dbe464cd9.png">

Is there a way to remove this error?

Swift-JWT version: 4.0.0
LoggerAPI version: 2.0.0

**Comment by dannys42** [comment]
Have you tried the suggestions in this thread? https://developer.apple.com/forums/thread/123614

**Comment by WeiLiangTan** [comment]
Methods I have tried
1. set "Build Active Architure Only" to Yes
    Tried but I still getting errors
2.  "Open with Rosseta"
    Currently using this method, it works, however this doesn't seems like a solution. And I noticed after turning on this option, the building time increase significantly
