### ISSUE TITLE
Controller Log Level not supported

### ISSUE THREAD

**Issue by tkhuran** [IBM-Swift/LoggerAPI#7]
LoggerAPI and HeliumLogger currently does not support log level controlling.

Example:
An app development life cycle goes from Dev -> Test -> Staging - > Prod. Now chart below shows the log levels for each of the environment that a developer wants to use, staring from Dev (maximum logging) to the Prod with the least logging (only the errors).

| Environment | Log Levels |
| --- | --- |
| DEV | .Verbose |
| TEST | .Debug |
| STAGE | .Warning |
| PROD | .Error |

The package currently does not support this feature.
# Proposed changes

``` swift
// Logger.swift
public enum LoggerMessageType: String {
    case Verbose = "VERBOSE"
    case Info = "INFO"
    case Debug = "DEBUG"
    case Warning = "WARNING"
    case Error = "ERROR"

// added the logger type function
    public func logType() -> Int {
        switch self {
        case .Verbose:
            return 1
        case .Info:
            return 2
        case .Debug:
            return 3
        case .Warning:
            return 4
        case .Error:
            return 5
        }
    }
}
```

``` swift
// Logger.swift
public class Log {
// your code goes here.
public class func debug(msg: String, functionName: String = #function,
        lineNum: Int = #line, fileName: String = #file) {
            logger?.log( .Debug, msg: msg,// corrected this line as it was using .Warning
                functionName: functionName, lineNum: lineNum, fileName: fileName)
    }
}
```

``` swift
// HeliumLogger.swift
// added the variable for including LoggerMessageType
private var type: LoggerMessageType = .Verbose
public init (_ type: LoggerMessageType) {
        self.type = type
    }

extension HeliumLogger : Logger {
// your code goes here
if type.logType() >= self.type.logType() { // controlled logging based on the environment
                if colored {
                    print ("\(color.rawValue) \(message) \(TerminalColor.Foreground.rawValue)")
                } else {
                    print (" \(message) ")
                }
        }
}
```

``` swift
// example
main() {
import LoggerAPI
import HeliumLogger
// Logging
        Log.logger = HeliumLogger(.Warning)
Log.verbose("VERBOSE")
Log.info("INFO")
Log.debug("DEBUG")
Log.warning("WARNING")
Log.error("ERROR")
}

// OUTPUT
WARNING
ERROR
```

**Comment by kweinmeister** [comment]
Do we need `logType()`? Can we instead simplify this as follows, and use the `.rawValue()` to get the integer value? Also, I have changed the enums to be lowerCamelCase per Swift 3 API guidelines.

```
public enum LoggerMessageType: Int {
    case verbose = 1`
    case info = 2
    case debug = 3
    case warning = 4
    case error = 5
```

Also including @rfdickerson.

**Comment by rfdickerson** [comment]
This looks good to me! Can we filter the output based on these logging issues in HeliumLogger?

**Comment by tkhuran** [comment]
@kweinmeister , if we define LoggerMessageType as Int then we still have to define the String values to support the message type printing on the console. I am good either ways.

**Comment by shmuelk** [comment]
I'm closing this issue. The PR that was merged fixes the problem.

Having said that we should look into @kweinmeister's suggestion. We should probably add a description function to the enum that dumps it as a String. See issue IBM-Swift/Kitura#523
