### ISSUE TITLE
swift build return "error: The dependency graph could not be satisfied"

### ISSUE THREAD

**Issue by euskadi31** [IBM-Swift/LoggerAPI#9]
My swift version: swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a

`error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/LoggerAPI.git)`

**Comment by dfirsht** [comment]
There should not be any dependency issues now.

**Comment by oliver-dew** [comment]
I'm getting the same error:

error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/LoggerAPI.git)

I'm following the Getting Started section in the README.md of github.com/IBM-Swift/Kitura
It builds and runs fine if I remove the HeliumLogger dependency

OS X 10.11
Swift version: DEVELOPMENT-SNAPSHOT-2016-07-25-a

EDIT: nevermind, if I update the HeliumLogger dependency to version 0.14, the dependency error goes away

**Comment by vadimeisenbergibm** [comment]
@Utsira I have submitted a PR to bump the version of helium logger in README - https://github.com/IBM-Swift/Kitura/pull/694. It should be 14 (minor version).

**Comment by oliver-dew** [comment]
Thanks! I think I wrote my edit at the same time as you were typing your reply. I just opened an issue on IBM-Swift/Kitura saying the same thing, I guess it can be closed/ merged into your PR. 

I just watched the WWDC server-side-swift video. Great stuff, excited to be getting started with Kitura.
